services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-login-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
